name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "@neynar/react"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: steps.release.outputs.releases_created != 'true'
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}